###
POST http://localhost:3000/create
content-type: application/json

{
  "url": "https://baidu.com",
  "slug": ""
}

###
GET http://localhost:3000/zfwowQ

###
GET www.xxx.com
token: 988d79c45c194968867ddc24e28235a4
